@extends('admin.layouts.app')

@section('title', 'Family Controls')

@section('content')
    @include('admin.adm.partials.nav')
    <div class="sibling-toolbar" aria-label="Sibling table tools"><button type="button" class="sibling-tool" data-sibling-export="copy" title="Copy"><i class="fa-regular fa-copy"></i></button><button type="button" class="sibling-tool" data-sibling-export="excel" title="Excel"><i class="fa-regular fa-file-excel"></i></button><button type="button" class="sibling-tool" data-sibling-export="csv" title="CSV"><i class="fa-regular fa-file-lines"></i></button><button type="button" class="sibling-tool" data-sibling-export="pdf" title="PDF"><i class="fa-regular fa-file-pdf"></i></button><button type="button" class="sibling-tool" data-sibling-export="print" title="Print"><i class="fa-solid fa-print"></i></button><button type="button" class="sibling-tool" data-sibling-export="columns" title="Columns"><i class="fa-solid fa-table-columns"></i></button><div class="sibling-column-menu hidden" data-column-menu></div></div>
    <section class="sibling-page mt-4 overflow-hidden rounded-xl border border-[#d8d8d8] bg-white shadow-sm">
        <div class="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-3"><h1 class="text-xl font-normal"><i class="fa-solid fa-user-group mr-2"></i>Sibling List</h1><div class="flex gap-2"><button type="button" class="sibling-primary" data-open-add><i class="fa-solid fa-plus mr-1"></i>Add Sibling</button><button type="button" class="sibling-orange" data-selected-pdf><i class="fa-solid fa-download mr-1"></i>Selected PDF</button><button type="button" class="sibling-orange" onclick="window.print()"><i class="fa-solid fa-print mr-1"></i>Family Report</button></div></div>
        <form method="GET" action="{{ route('admin.adm.siblings.index') }}" class="flex flex-wrap gap-3 border-b bg-[#fafafa] px-4 py-3"><select name="brc_id" class="sibling-control"><option value="">All Branches</option>@foreach ($branches as $branch)<option value="{{ $branch->id }}" @selected((string) $branchId === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" class="sibling-control min-w-[250px]" placeholder="Search code, name, CNIC or phone"><button class="sibling-primary" type="submit">Search</button></form>
        <div class="overflow-x-auto"><table class="w-full min-w-[1050px] border-separate border-spacing-0 text-sm"><thead><tr class="bg-[#26408d] text-white"><th class="sibling-th"><input type="checkbox" id="sibling-select-all"> #</th><th class="sibling-th">Branch</th><th class="sibling-th">Sibling Information</th><th class="sibling-th">Sibling Member</th><th class="sibling-th">Sibling Member Information</th><th class="sibling-th">Login</th><th class="sibling-th text-right">Action</th></tr></thead><tbody>
        @forelse ($siblings as $sibling)
            <tr><td class="sibling-td"><input type="checkbox" class="sibling-check" value="{{ $sibling->id }}"> {{ $siblings->firstItem() + $loop->index }}</td><td class="sibling-td">{{ $branches->firstWhere('id', $sibling->brc_id)->name ?? 'N/A' }}</td><td class="sibling-td leading-6">Code: {{ $sibling->sibling_code }}<br>Name: {{ $sibling->sibling_name }}<br>CNIC: {{ $sibling->sibling_cnic }}<br>Phone: {{ $sibling->sibling_phone }}</td><td class="sibling-td">{{ $sibling->member_count }}</td><td class="sibling-td">@forelse ($sibling->members as $member)<div>{{ trim($member->firstname.' '.$member->lastname) }} <b class="text-[#2596be]">({{ $member->admission_no }})</b> <b class="text-red-600">({{ $member->class }} - {{ $member->section }})</b></div>@empty<span class="text-neutral-500">No active students</span>@endforelse</td><td class="sibling-td">@if ($sibling->login)Username: {{ $sibling->login->username }}<br>Password: {{ $sibling->login->password }}@endif</td><td class="sibling-td whitespace-nowrap text-right"><button type="button" class="sibling-action sibling-edit" title="Edit" data-edit-id="{{ $sibling->id }}" data-edit-name="{{ $sibling->sibling_name }}" data-edit-cnic="{{ $sibling->sibling_cnic }}" data-edit-phone="{{ $sibling->sibling_phone }}" data-edit-students='@json($sibling->members->values())'><i class="fa-solid fa-pencil"></i></button><form class="inline" method="POST" action="{{ route('admin.adm.siblings.destroy', $sibling) }}" onsubmit="return confirm('Are you sure you want to delete this record?')">@csrf @method('DELETE')<button class="sibling-action sibling-delete" title="Delete"><i class="fa-solid fa-xmark"></i></button></form></td></tr>
        @empty
            <tr><td colspan="7" class="px-4 py-10 text-center text-neutral-500">No siblings found.</td></tr>
        @endforelse
        </tbody></table></div><div class="border-t px-4 py-3">{{ $siblings->links() }}</div>
    </section>

    <div class="sibling-modal hidden" id="add-sibling-modal"><div class="sibling-dialog"><div class="flex justify-between border-b p-4"><h2 class="font-semibold">Add Sibling</h2><button type="button" data-close-modal>&times;</button></div><form method="POST" action="{{ route('admin.adm.siblings.store') }}" class="grid gap-4 p-4">@csrf<label>Branch<select name="brc_id" class="sibling-control">@foreach ($branches as $branch)<option value="{{ $branch->id }}" @selected((string) $branchId === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select></label><label>Sibling Code<input name="sibling_code" value="{{ $nextCode }}" readonly class="sibling-control"></label><label>Father Name<input name="sibling_name" class="sibling-control" required></label><label>Father CNIC<input name="sibling_cnic" class="sibling-control" required></label><label>Father Phone<input name="sibling_phone" class="sibling-control" required></label><label>Associate Students<select name="student_session_ids[]" multiple class="sibling-control min-h-32">@foreach ($students as $student)<option value="{{ $student->student_session_id }}">{{ $student->admission_no }} - {{ trim($student->firstname.' '.$student->lastname) }} - {{ $student->father_name }} - {{ $student->class }} ({{ $student->section }})</option>@endforeach</select></label><div class="text-right"><button class="sibling-primary" type="submit">Save</button><button class="sibling-cancel ml-2" type="button" data-close-modal>Cancel</button></div></form></div></div>

    <div class="sibling-modal hidden" id="edit-sibling-modal"><div class="sibling-dialog"><div class="flex justify-between border-b p-4"><h2 class="font-semibold">Edit Sibling</h2><button type="button" data-close-modal>&times;</button></div><form id="edit-sibling-form" class="grid gap-4 p-4"><input type="hidden" name="brc_id" value="{{ $branchId }}"><input type="hidden" name="sibling_code" id="edit-code" value="1"><label>Father Name<input name="sibling_name" id="edit-name" class="sibling-control" required></label><label>Father CNIC<input name="sibling_cnic" id="edit-cnic" class="sibling-control" required></label><label>Father Phone<input name="sibling_phone" id="edit-phone" class="sibling-control" required></label><div><label>Current Students</label><div id="edit-current-students" class="sibling-current"></div></div><label>Add Students<select name="student_session_ids[]" id="edit-students" multiple class="sibling-control min-h-32">@foreach ($students as $student)<option value="{{ $student->student_session_id }}">{{ $student->admission_no }} - {{ trim($student->firstname.' '.$student->lastname) }} - {{ $student->class }} ({{ $student->section }})</option>@endforeach</select></label><div class="text-right"><button class="sibling-primary" type="submit">Save</button><button class="sibling-cancel ml-2" type="button" data-close-modal>Cancel</button></div></form></div></div>
@endsection

@push('styles')
<style>
.sibling-toolbar{position:relative;display:flex;justify-content:flex-end;gap:6px;border:1px solid #d8d8d8;border-radius:0 0 8px 8px;background:#fff;padding:10px 14px}.sibling-tool{width:36px;height:36px;border:0;border-radius:5px;background:#26408d;color:#fff;cursor:pointer;transition:transform .15s ease,filter .15s ease}.sibling-tool:hover{filter:brightness(1.15);transform:translateY(-2px)}.sibling-column-menu{position:absolute;right:14px;top:52px;z-index:10;min-width:180px;border:1px solid #d8d8d8;border-radius:5px;background:#fff;padding:8px;color:#222;box-shadow:0 4px 12px #0002}.sibling-column-menu label{display:block;padding:4px}.sibling-column-menu.hidden{display:none}
.sibling-control{width:100%;border:1px solid #cfcfcf;border-radius:4px;background:#fff;padding:.62rem .75rem;outline:0}.sibling-control:focus{border-color:#26408d;box-shadow:0 0 0 2px #26408d22}.sibling-primary,.sibling-orange,.sibling-action,.sibling-cancel{border:0;border-radius:4px;padding:.55rem .8rem;cursor:pointer;transition:transform .15s ease,filter .15s ease}.sibling-primary{background:#26408d;color:#fff}.sibling-orange{background:#f39c12;color:#fff}.sibling-cancel{background:#e5e7eb}.sibling-primary:hover,.sibling-orange:hover,.sibling-action:hover,.sibling-cancel:hover{filter:brightness(1.1);transform:translateY(-1px)}.sibling-th{padding:.8rem;text-align:left;border-right:1px solid #ffffff2e;white-space:nowrap}.sibling-td{padding:.75rem;border-right:1px solid #e7cfcf;border-bottom:1px solid #e7cfcf;background:#f7e3e3;vertical-align:top}.sibling-action{display:inline-flex;width:30px;height:30px;align-items:center;justify-content:center;color:#fff}.sibling-edit{background:#26408d}.sibling-delete{background:#ef5b4c}.sibling-modal{position:fixed;inset:0;z-index:50;display:flex;align-items:center;justify-content:center;background:#0008;padding:1rem}.sibling-modal.hidden{display:none}.sibling-dialog{width:min(720px,100%);max-height:90vh;overflow:auto;border-radius:8px;background:#fff;box-shadow:0 12px 30px #0004}.sibling-current{max-height:160px;overflow:auto;border:1px solid #ddd;padding:.5rem}.sibling-current-row{display:flex;gap:.5rem;border-bottom:1px solid #eee;padding:.35rem}
</style>
@endpush

@push('scripts')
<script src="{{ asset('assets/dist/datatables/js/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/dist/datatables/js/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/js/siblings-directory.js') }}"></script>
@endpush
